### ISSUE TITLE
Incorrect dependencies for some useEffect hooks used in the application

### ISSUE THREAD

**Issue by maverickamit** [0xAegis/frontend#36]

**Comment by maverickamit** [comment]
> 
Opened a long time ago, probably fixed already. 
But some functions are still not using any dependency array. Which means it's being run on every render. Have to check if that is necessary.

**Comment by SkullTech** [comment]
> Opened a long time ago, probably fixed already. But some functions are still not using any dependency array. Which means it's being run on every render. Have to check if that is necessary.

I think having no dependency array means it will run only the first time the component gets loaded, whereas having an empty list as dependency array means it will run on every render.

**Comment by maverickamit** [comment]
It's the opposite.
